%%%% This file is automatically generated by genMscript.pl
%%%% Please do not modify.
%%%% input command: ./gencalcAdj.pl moss/data10
%%%%%% Calculate adjacency matrix for f files.
M = 1000;
N = 6088;
nzmax = 756668;
Af = readsp('moss/data10/ftr.', nzmax, M, N);
Wf = Af' * Af;
save moss/data10/mats/Wf.mat Wf
clear Wf
M = 1000;
N = 6088;
nzmax = 3637000;
Afobs = readsp('moss/data10/fobs.', nzmax, M, N);
Wfobs = Afobs' * Afobs;
save moss/data10/mats/Wfobs.mat Wfobs
clear Wfobs
Wfcross = Afobs' * Af;
save moss/data10/mats/Wfcross.mat Wfcross
clear Afobs Af Wfcross

%%%%%% Calculate adjacency matrix for s files.
M = 1000;
N = 25783;
nzmax = 204700;
As = readsp('moss/data10/str.', nzmax, M, N);
Ws = As' * As;
save moss/data10/mats/Ws.mat Ws
clear Ws
M = 1000;
N = 25783;
nzmax = 22718219;
Asobs = readsp('moss/data10/sobs.', nzmax, M, N);
Wsobs = Asobs' * Asobs;
save moss/data10/mats/Wsobs.mat Wsobs
clear Wsobs
Wscross = Asobs' * As;
save moss/data10/mats/Wscross.mat Wscross
clear Asobs As Wscross

%% Calculate correlation matrices.
disp('Calculating correlation matrices.');
load moss/data10/mats/Wf.mat
load moss/data10/mats/Wfobs.mat
load moss/data10/mats/Wfcross.mat
load moss/data10/mats/Ws.mat
load moss/data10/mats/Wsobs.mat
load moss/data10/mats/Wscross.mat
calcCorr
save moss/data10/mats/Cov.mat Cov
save moss/data10/mats/rho.mat rho
save moss/data10/mats/condprob.mat PAB
%% Do spectral clustering.
disp('Doing spectral clustering.');
runspeccluster
predfn = 'moss/data10/predinds.txt';
fd = fopen(predfn, 'w');
for i = 1:N, fprintf (fd, '%d\n', i); end;
fclose (fd);
printspeccluster(rho, bestgroups, bestK, 'moss/data10', '1-0.25', predfn, predfn);


M = 1000;
N = 6088;
nzmax = 756668;
Af = readsp('moss/data10/ftr.', nzmax, M, N);
printClusterSummary(Af, bestgroups, bestK, 'moss/data10', '1-0.25');
