%%%% This file is automatically generated by genMscript.pl
%%%% Please do not modify.
%%%% input command: ./gencalcAdj.pl rb/fix2
addpath ../graphalgs
%%%%%% Calculate adjacency matrix for f files.
M = 14;
N = 333;
nzmax = 1842;
Af = readsp('rb/fix2/ftr.', nzmax, M, N);
Wf = Af' * Af;
save rb/fix2/mats/Wf.mat Wf
clear Wf
M = 14;
N = 333;
nzmax = 4437;
Afobs = readsp('rb/fix2/fobs.', nzmax, M, N);
Wfobs = Afobs' * Afobs;
save rb/fix2/mats/Wfobs.mat Wfobs
clear Wfobs
Wfcross = Afobs' * Af;
save rb/fix2/mats/Wfcross.mat Wfcross
clear Afobs Af Wfcross

%%%%%% Calculate adjacency matrix for s files.
M = 14;
N = 16468;
nzmax = 37217;
As = readsp('rb/fix2/str.', nzmax, M, N);
Ws = As' * As;
save rb/fix2/mats/Ws.mat Ws
clear Ws
M = 14;
N = 16468;
nzmax = 230552;
Asobs = readsp('rb/fix2/sobs.', nzmax, M, N);
Wsobs = Asobs' * Asobs;
save rb/fix2/mats/Wsobs.mat Wsobs
clear Wsobs
Wscross = Asobs' * As;
save rb/fix2/mats/Wscross.mat Wscross
clear Asobs As Wscross

%% Calculate correlation matrices.
disp('Calculating correlation matrices.');
load rb/fix2/mats/Wf.mat
load rb/fix2/mats/Wfobs.mat
load rb/fix2/mats/Wfcross.mat
calcCorr
save rb/fix2/mats/Cov.mat Cov
save rb/fix2/mats/rho.mat rho
save rb/fix2/mats/condprob.mat PAB
%% save output in text format
N = size(rho, 1);
fd = fopen('rb/fix2/mats/rho.dat','w');
for i = 1:N, for j = 1:N,
fprintf (fd, '%.15g ', rho(i,j));
end;
fprintf(fd, '\n');
end;
fclose(fd);


%% Do spectral clustering.
disp('Doing spectral clustering.');
K = 10; sigma = 0.25;
A = exp(rho/(2*sigma^2));
for i = 1:N, A (i,i) = 0; end;
[Y,groups] = ngspec(A,K);
predfn = 'rb/fix2/predinds.txt';
fd = fopen(predfn, 'w');
for i = 1:N, fprintf (fd, '%d\n', i); end;
fclose (fd);
printspeccluster(rho, groups, K, 'rb/fix2', '1-0.25', predfn, predfn);


