name := rhythmbox
schemes := all branches returns scalar-pairs
experiment := /moa/sc5/cbi/best-known-datasets/$(name)
source-strip-prefixes := ../../src/ ../../../src/ ../../../../src/

-include ../../site-rules.mk
-include site-rules.mk

include ../../src/analysis-rules.mk
