name := rhythmbox
schemes := all branches returns scalar-pairs
source-strip-prefixes := ../../src/ ../../../src/ ../../../../src/

-include ../../site-rules.mk
-include site-rules.mk

include ../../src/analysis-rules.mk
