#!/usr/bin/perl -w

use strict;


########################################################################


die "Usage: $0 <sparsity> <threshhold>\n"
    unless @ARGV == 2;

my ($sparsity, $threshhold) = @ARGV;


########################################################################


local ($,, $\) = ("\t", "\n");

while (<STDIN>) {
    chomp;
    my ($unit, $site, $count) = split /\t/;
    my $rate = $count > $threshhold ? (1 / $sparsity) : 1;
    print $unit, $site, $rate;
}
