Import('env')
env = env.Clone(
    LIBS=['corrective', 'analyze', 'dl'],
    LIBPATH=['..', '.'],
)

env.StaticLibrary('corrective', [
	'Complex.cc',
	'Candidates.cc',
	'Conjunction.cc',
	'Disjunction.cc',
	'Outcome.cc',
	'Predicate.cc',
	'RunSet.cc',
	'RunSuite.cc',
	'allFailures.cc',
	'main.cc',
	'zoom.cc',
        ])

for variant in ['exact-complete', 'approximate-complete', 'adaptive-sampled']:
    Default(env.Program('%s.cc' % variant))
