#!/usr/bin/perl -w

use strict;

use FileHandle;
use FindBin;


########################################################################


@ARGV == 1 or die "Usage: $0 <num-runs>\n";
my $numRuns = shift;


########################################################################


my $datadir = "$FindBin::Bin/../data";

foreach my $runId (0 .. $numRuns - 1) {
    my $filename = "$datadir/$runId/bad/stderr";
    my $stderr = new FileHandle $filename;
    if ($stderr) {
	while (<$stderr>) {
	    next unless /^Error (\d)+:/;
	    print "$runId\t$1\n";
	}
    } else {
	warn "cannot read $filename: $!\n";
    }
}
