# the variables below must be set
numbugaspects :=
numaspects :=

# cbiexp root, reset if your cbiexp root is different
root := ../..

# the variables below may be overridden
# set nonormalize to anything and run counts will not be normalized
# nonormalize :=

# set maxiterations to the maximum number of iterations desired
# if the likelihood change falls below minlikelihood change, algorithm will
# terminate early
# maxiterations :=

# set minlikelihoodchange lower to get more iterations, higher to get fewer 
# minlikelihoodchange :=

# set numrestarts to the number of restarts desired
# numrestarts :=

# analysisdir contains the .mat files input to this analysis 
# analysisdir :=

-include $(root)/src/plsa/analysis-rules.mk
