Import('env', 'lib')

File([
        'Location.h',
        'Locations.h',
        'README',
        'Reader.h',
        ])

sources = [
    'Location.cc',
    'Locations.cc',
    'Reader.cc',
    'main.cc',
    ]

Default(
    env.Program(
        'never-reached', sources,
        LIBS=lib.name,
        LIBPATH=lib.dir,
        RPATH=lib.dir.abspath,
        )
    )
