Import('env')

sources = [
    'Location.cc',
    'Locations.cc',
    'Reader.cc',
    'main.cc',
    ]

Default(
    env.Program(
        'never-reached', sources,
        LIBS=['analyze', 'dl'],
        )
    )
