name := exif
experiment := /moa/sc5/cbi/best-known-datasets/$(name)
schemes := all branches scalar-pairs
source-strip-prefixes := ../../../../src/ ../../../src/

-include ../../site-rules.mk
-include site-rules.mk

include ../../src/analysis-rules.mk
