Import('env')

env.StaticLibrary('Score', [
        'Fail.cc',
	'HarmonicMeanLog.cc',
	'HarmonicMeanSqrt.cc',
	'Importance.cc',
	'Increase.cc',
	'LowerBound.cc',
	'LowerTimesFails.cc',
	'TrueInFails.cc',
        ])
