name := bc
schemes := all branches returns scalar-pairs
experiment := /moa/sc5/cbi/best-known-datasets/$(name)
source-strip-prefixes := /data/alicez/proj/cbiexp/bc/src/

include ../../src/analysis-rules.mk
