name := bc
schemes := all branches returns scalar-pairs
experiment := /moa/sc2/alicez/$(name)
source-strip-prefixes := ../../src/
report-series := inverse-100
training-runs := 1000

-include ../../site-rules.mk
-include site-rules.mk
include ../../src/analysis-rules.mk
