name := ccrypt
experiment := /moa/sc5/cbi/best-known-datasets/$(name)
schemes := all branches returns scalar-pairs
source-strip-prefixes := /data/alicez/cbiexp/ccrypt/src/src/

include ../../src/analysis-rules.mk
