name := ccrypt
schemes := all branches returns scalar-pairs
source-strip-prefixes := ../../src/
report-series := inverse-100
training-runs := 1000

-include ../../site-rules.mk
-include site-rules.mk
include ../../src/analysis-rules.mk
