#!/usr/bin/perl -w

use strict;


########################################################################


die "Usage: $0 <sparsity>\n"
    unless @ARGV == 1;

my ($sparsity) = @ARGV;


########################################################################


local ($,, $\) = ("\t", "\n");

my $max = 1;
my $min = 1 / $sparsity;

while (<STDIN>) {
    chomp;
    my ($unit, $site, $count) = split /\t/;;
    my $rate = $sparsity / $count;
    if ($rate < $min) {
	$rate = $min;
    } elsif ($rate > $max) {
	$rate = $max;
    }
    print $unit, $site, $rate;
}
