main()
{
    fprintf(result_summary_fp, "<table border=1>\n<tr>\n"
                               "<td></td>\n"
                               "<td align=middle>lower bound of<br>confidence interval</td>\n"
                               "<td align=middle>increase<br>score</td>\n"
                               "<td align=middle>fail<br>score</td>\n"
                               "<td align=middle>true in<br># F runs</td>\n"
                               "</tr>\n<tr>\n"
                               "<td>branch</td>\n"
                               "<td align=middle><a href=\"B_lb.html\">X</a></td>\n"
                               "<td align=middle><a href=\"B_is.html\">X</a></td>\n"
                               "<td align=middle><a href=\"B_fs.html\">X</a></td>\n"
                               "<td align=middle><a href=\"B_nf.html\">X</a></td>\n"
                               "</tr>\n<tr>\n"
                               "<td>return</td>\n"
                               "<td align=middle><a href=\"R_lb.html\">X</a></td>\n"
                               "<td align=middle><a href=\"R_is.html\">X</a></td>\n"
                               "<td align=middle><a href=\"R_fs.html\">X</a></td>\n"
                               "<td align=middle><a href=\"R_nf.html\">X</a></td>\n"
                               "</tr>\n<tr>\n"
                               "<td>scalar</td>\n"
                               "<td align=middle><a href=\"S_lb.html\">X</a></td>\n"
                               "<td align=middle><a href=\"S_is.html\">X</a></td>\n"
                               "<td align=middle><a href=\"S_fs.html\">X</a></td>\n"
                               "<td align=middle><a href=\"S_nf.html\">X</a></td>\n"
                               "</tr>\n<tr>\n"
                               "<td>all</td>\n"
                               "<td align=middle><a href=\"all_lb.html\">X</a></td>\n"
                               "<td align=middle><a href=\"all_is.html\">X</a></td>\n"
                               "<td align=middle><a href=\"all_fs.html\">X</a></td>\n"
                               "<td align=middle><a href=\"all_nf.html\">X</a></td>\n"
                               "</tr>\n</table>\n</body></html>\n");
}

