from os.path import realpath
from sys import stderr

import SCons.Warnings as Warnings

Import('env')


class MissingCodeSurferWarning(Warnings.Warning):
    pass


if env.get('csurf'):
    csurf = realpath(env['csurf'])
    include = File(csurf).dir.dir.Dir('include')
    env.SharedLibrary('effort.cc', CPPPATH=['$CPPPATH', include], LIBS='analyze')
else:
    Warnings.enableWarningClass(MissingCodeSurferWarning)
    Warnings.warn(MissingCodeSurferWarning, 'cannot find CodeSurfer, so skipping effort plugin')
