Import('env', 'lib')

Glob('*.m')
File([
        'README',
        'process.xml',
        ])

Default(
    env.Program(
        'make-counts-matrix',
        'make_counts_matrix.cc',
        LIBS=[lib.name, 'sqlite3'],
        LIBPATH=lib.dir,
        RPATH=lib.dir.abspath,
        )
    )
